---
title: "ray"
author: "Ray Wen"
date: "3/18/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
library(ggplot2)
library("readxl")
library(dplyr)
library(tidyverse)
library(vtable)

```

Load Data
```{r}
raw_data <- read.csv("../data/raw_gss.csv")
```


plot
```{r}
# Mental Health Male vs Female

male_female_mental <- raw_data %>% select(c(hlthmntl, sex)) %>%
  mutate(sex = case_when(
    sex == 1 ~ "Male",
    sex == 2 ~ "Female",
    sex == 3 ~ "Transgender",
    sex == 4 ~ "None of these",
  )) %>% group_by(sex)

male_female_mental %>% ggplot(aes(x=hlthmntl, fill=sex)) +
  geom_histogram(aes(y = ..density..), position = 'dodge')
```


mental health vs age groups

```{r}
age_group <- raw_data %>% select(c(hlthmntl, age)) %>%
  mutate(age = case_when(
    age < 20 ~ "< 20",
    age < 30 ~ "< 30",
    age < 40 ~ "< 40",
    age < 50 ~ "< 50",
    age < 60 ~ "< 60",
    age >= 60 ~ ">= 60",
  )) %>% group_by(age)

age_group %>% ggplot(aes(x=hlthmntl, fill=age)) +
  geom_histogram(aes(y = ..density..), position = 'dodge')
```

Mental vs physical 

```{r}
mental_phsy <- raw_data %>% select(c(hlthmntl, hlthphys, age, sex)) %>%
  mutate(age = case_when(
    age < 20 ~ "< 20",
    age < 30 ~ "< 30",
    age < 40 ~ "< 40",
    age < 50 ~ "< 50",
    age < 60 ~ "< 60",
    age >= 60 ~ ">= 60",
  )) %>%
  mutate(sex = case_when(
    sex == 1 ~ "Male",
    sex == 2 ~ "Female",
    sex == 3 ~ "Transgender",
    sex == 4 ~ "None of these",
  ))

mental_phsy  %>% ggplot(aes(x=hlthmntl, y=hlthphys)) +
  geom_point(aes(color=age), position = 'dodge')
  
```


sexual orientation

```{r}
sexornt_data <- raw_data %>% select(c(sexornt, hlthmntl)) %>% filter(!is.na(sexornt), !is.na(hlthmntl)) %>%
  mutate(sexornt = case_when(
    sexornt <= 2 ~ "LGBTQ+",
    sexornt == 3 ~ "Heterosexual",
  )) %>%
  mutate(mntl_poor = case_when(
    hlthmntl <= 3 ~ 'Good',
    hlthmntl >= 4 ~ 'Not Good',
  ))

sexornt_data %>% ggplot(aes(x= mntl_poor,  group=sexornt))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
  geom_text(aes( label = scales::percent(..prop..),
                 y= ..prop.. ), stat= "count", vjust = -.5) +
  labs(y = "Percent", fill="mntl_poor") +
  facet_grid(~sexornt) +
  scale_y_continuous(labels = scales::percent)
```


EDA

```{r}

# % missing hlthmntl entries 0.09
n <- length(raw_data$hlthmntl)
length(which(is.na(raw_data$hlthmntl)))/n

```



```{r}
class_data <- raw_data %>% select(c(hlthmntl, class1)) %>% filter(!is.na(class1), !is.na(hlthmntl)) %>%
  mutate(class_d = case_when(
    class1 == 1 ~ "lower",
    class1 == 2 ~ "working",
    class1 == 3 ~ "lower middle",
    class1 == 4 ~ "middle",
    class1 == 5 ~ "upper middle",
    class1 == 6 ~ "upper",
    
  )) %>%
  mutate(mntl_poor = case_when(
    hlthmntl <= 3 ~ 'Good',
    hlthmntl >= 4 ~ 'Not Good',
  ))
  
class_data %>% ggplot(aes(x=hlthmntl, fill=class_d)) +
  geom_histogram(aes(y = ..density..), position = 'dodge')

class_data %>% ggplot(aes(x= mntl_poor,  group=class_d))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
  geom_text(aes( label = scales::percent(..prop..),
                 y= ..prop.. ), stat= "count", vjust = -.5) +
  labs(y = "Percent", fill="mntl_poor") +
  facet_grid(~class_d) +
  scale_y_continuous(labels = scales::percent)
```



```{r}
income_data <- raw_data %>% select(c(hlthmntl, income16)) %>% filter(!is.na(income16), !is.na(hlthmntl)) %>%
  mutate(income = case_when(
    income16 <= 8 ~ "< $10,000",
    income16 <= 12 ~ "$10,000 - $20,000",
    income16 <= 17 ~ "$20,000 - $40,000",
    income16 <= 19 ~ "$40,000 - $60,000",
    income16 <= 21 ~ "$60,000 - $90,000",
    income16 > 21 ~ "> $90,000",
    
  )) %>%
  mutate(mntl_poor = case_when(
    hlthmntl <= 3 ~ 'Good',
    hlthmntl >= 4 ~ 'Not Good',
  ))
  
income_data %>% ggplot(aes(x=hlthmntl, fill=income)) +
  geom_histogram(aes(y = ..density..), position = 'dodge', alpha=1)

income_data %>% ggplot(aes(x= mntl_poor,  group=income))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
  geom_text(aes( label = scales::percent(..prop..),
                 y= ..prop.. ), stat= "count", vjust = -.5) +
  labs(y = "Percent", fill="mntl_poor") +
  facet_grid(~income) +
  scale_y_continuous(labels = scales::percent)
```


```{r}
first_born <- raw_data %>% select(c(hlthmntl, agekdbrn)) %>% filter(!is.na(agekdbrn), !is.na(hlthmntl)) %>%
  mutate(born = case_when(
    agekdbrn < 18 ~ '< 18',
    agekdbrn >= 18 & agekdbrn <= 29 ~ '18-29',
    agekdbrn >= 30 & agekdbrn <=39~ '30-39',
    agekdbrn >= 40 & agekdbrn <=49~ '40-49',
    agekdbrn >= 50 & agekdbrn <=64~ '50-64',
    agekdbrn >= 65 & agekdbrn <=89~ '65-89'
  )) %>%
  mutate(mntl_poor = case_when(
    hlthmntl <= 3 ~ 'Good',
    hlthmntl >= 4 ~ 'Not Good',
  ))
  
first_born %>% ggplot(aes(x=hlthmntl, fill=born)) +
  geom_histogram(aes(y = ..density..), position = 'dodge')

first_born %>% ggplot(aes(x= mntl_poor,  group=born))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") +
  geom_text(aes( label = scales::percent(..prop..),
                 y= ..prop.. ), stat= "count", vjust = -.5) +
  labs(y = "Percent", fill="mntl_poor") +
  facet_grid(~born) +
  scale_y_continuous(labels = scales::percent)
```


# Older ppl % in upper class
```{r}
old_upper <- raw_data %>% select(c(age, class1))

length(which(old_upper$age > 50 & old_upper$class1 == 6)) / length(which(old_upper$class1 == 6))
```















